image: nfcore/gitpod:latest

# Manual Quarto install - mamba version doesn't work correctly
tasks:
  - name: Install Quarto
    command: |
      wget https://quarto.org/download/latest/quarto-linux-amd64.deb
      sudo dpkg -i quarto-linux-amd64.deb
      quarto check all
      rm quarto-linux-amd64.deb

vscode:
  extensions:
    - quarto.quarto
    - esbenp.prettier-vscode
    - nextflow.nextflow
