project:
  type: website

website:
  title: "How to use this template"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: working_habits.qmd
        text: Habits
      - href: starting_steps.qmd
        text: Begin
      - href: test_dataset.qmd
        text: Test-Data
      - href: computation_environment.qmd
        text: Environment
      - href: prototyping.qmd
        text: Prototyping
      - href: troubleshooting.qmd
        text: Troubleshoot
      - href: references.qmd
        text: Reference
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: auto

