project:
  type: book

book:
  title: "How to use this template"
  page-navigation: true
  sidebar:
    title: Usage
    search: true
  chapters:
    - index.qmd
    - working_habits.qmd
    - starting_steps.qmd
    - test_dataset.qmd
    - computation_environment.qmd
    - prototyping.qmd
    - troubleshooting.qmd
    - references.qmd
    - about.qmd
  repo-url: https://github.com/mahesh-panchal/NBIS_project_template
  repo-actions: [edit, issue]
  repo-subdir: docs/how-to

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: auto

