## Workflow inputs
## The absolute path (full path, begins with / ) to the input data
samples: ''

## Workflow outputs
## The absolute path (full path, begins with / ) to the results folder
## If you have a NAISS Storage allocation, use that!
results: '/proj/naiss20xx-yy-zz/NBIS_support_<id>_results'

## Uppmax cluster configuration
## UPPMAX project - Needed only when running on an UPPMAX cluster
# project : 'naiss2021-YY-ZZ'
